near/near-jsonrpc-client-rs

- src/methods.rs
Add generic documentation on all methods in `near_jsonrpc_client::methods`... primarily for clarity. Showing which exported type does what. Disambiguating between `Rpc*Request` / `Rpc*Response` & `Rpc*Error` types.
> ## Module near_jsonrpc_client::methods::`broadcast_tx_async`
> ### Example
> 
> ```rust
> use near_jsonrpc_client::{errors, methods, JsonRpcClient, JsonRpcMethodCallResult};
> 
> use methods::broadcast_tx_async::{
>     RpcBroadcastTxAsyncRequest,
>     CryptoHash,
>     RpcBroadcastTxAsyncError,
> };
> 
> let mainnet_client = JsonRpcClient::new().connect("https://rpc.mainnet.near.org");
> 
> let request = RpcBroadcastTxAsyncRequest {...}; // <-- create a valid request here
> 
> let result: errors::JsonRpcMethodCallResult<
>     CryptoHash,
>     RpcBroadcastTxAsyncError,
> > …
```
> doc(methods): add generic documentation on all rpc methods

- README.md
- src/lib.rs
- src/methods.rs
This PR;
- Implements new traits `RpcHandlerRequest` and `RpcHandlerError` on all traits across the board for each method. Allowing for smarter static type checking and request/error transformers.
- Doubles down on the previously heavy usage of macros.
- As a consequence of this, we're also dropping auto-generated documentation. Probably for the best, anyways. We'll include more specific documentation and examples later down the line.
- Implements `RpcMethod` for `&T` so you can `call(request)` and optionally, `call(&request)` depending on the context you're in
- Adds a raw error parser for `RpcTransactionError` since it's `error.data` field contains a `ServerError::TxExecutionError`
> refactor(methods): promote use of traits, double down on the macro complexity

- Cargo.toml
- README.md
- src/lib.rs
- src/methods.rs
Prior to this, you could only construct requests using the predefined types in `method::*`. https://github.com/near/near-jsonrpc-client-rs/commit/70f05ae20c672098a1c875a6c88759dbccf08b33 saw the introduction of support for legacy patterns (behind a feature flag, of course).
This extends that capability to support generic method names. In the case where the method name doesn't exist, we return a  [`RpcRequestValidationErrorKind::MethodNotFound`](https://github.com/near/nearcore/blob/master/chain/jsonrpc-primitives/src/errors.rs#L39).
`legacy`: `client.call(methods::block::by_id(id))`
`legacy`: `client.call(methods::query::by_path(path, data))`
`all`: `client.call(methods::all("block", json!([id])))`
`all`: `client.call(methods::all("query", json!([path, data])))`
> feat: allow construction of generic method requests

- README.md
- src/lib.rs
- src/methods.rs
Impl smarter Any, providing a generic path for constructing requests + response/error deserialization
```rust
let result = client.call(methods::any::<
methods::block::RpcBlockResponse,
methods::block::RpcBlockError,
>("block", json!([BlockId::Height(0)])));
```
- One option, is an already well-defined `RpcMethod`
This would use the predefined `RpcMethod::Response` and `RpcMethod::Error` types. Which, more or less expands to the example above.
```rust
let result = client.call(methods::any::<methods::block::RpcBlockResult>(
"block",
json!([BlockId::Height(0)]),
));
```
- Another option, offering flexibility, is a custom result + error type.
```rust
#[derive(Deserialize)]
struct CustomBlockLookupResult {
author: AccountId,
}
let result = client.call(methods::any::<(
CustomBlockLookupResult, …
```
> feat: impl smarter Any result descriptors

- src/auth.rs
- src/lib.rs
This makes the auth interface more generic, primarily to extend the flexibility of custom implementations. Allowing them to be able to customize their header names.
```rust
use near_jsonrpc_client::auth;
struct CustomUserAuth {
username: String,
password: zeroize::Zeroizing<String>
}
impl auth::AuthScheme for CustomUserAuth {
fn get_auth_header(&self) -> auth::AuthHeaderEntry {
auth::AuthHeaderEntry {
header: "Authorization".to_string(),
token: format!("Basic {}", base64::encode(format!("{}:{}", self.username, *self.password))),
}
}
}
let client = JsonRpcClient::connect("http://localhost:3030")
.auth(CustomUserAuth { username: "root", password: "n1c3_try".to_string().into() });
```
Also replaces `Authorization: Basic <token>` with `x-api-key: <token>`.
```rust
let client = …
```
> feat: make auth interface more generic

- src/methods.rs
A number of error types in nearcore's jsonrpc have the `UnknownBlock` variant that has a field `error_message` that's skipped when serializing. Which leads to issues from the client attempting to deserialize thsose types' variants.
This patch implements a workaround for all types like that: when a partially serialized error variant is returned, an empty string for an error message is assumed unless one was returned by the server.
Resolves https://github.com/near/near-jsonrpc-client-rs/issues/28
> fix: mitigate deserialization of partially serialized error types

- Cargo.toml
Updated deps here.
@miraclx any reason why the lock file is in `.gitignore`?
> chore: dependencies updated

- src/methods.rs
A couple of RPC methods do not have an error equivalent. Notably: `broadcast_tx_async`, `EXPERIMENTAL_genesis_config` and adversarial methods. In each case, we use the unit `()` type to signify the absense of an error type.
But this is insufficient. Particularly given the fact that `std::error::Error` hinges on `fmt::Display` which requires each handler error to be itself `fmt::Display`-able. Which is not the case with `()`.
This PR implements a workaround by using a custom, non-constructable unit type with a custom `fmt::Display` implementation that would never be called. If ever, that results in a hard error.
> ensure None-typed errors are actual errors (displayable, etc.)

- Cargo.toml
- README.md
- src/methods.rs
- Update nearcore version to `0.11.0` (https://github.com/near/nearcore/pull/5943).
- Fixed `chunk` method serialization. https://github.com/near/near-jsonrpc-client-rs/commit/f40ad743653ad2a1a9eb5eaa96c302c9b531bf40
- `Client::call` no longer consumes the client. https://github.com/near/near-jsonrpc-client-rs/commit/471a53be062e0880c6bc5c2721d123da2a9e0c2e
- Implemented workaround for partially serialized server responses. https://github.com/near/near-jsonrpc-client-rs/pull/29
- Dropped base64 api token support in favor of a generic key-value approach. https://github.com/near/near-jsonrpc-client-rs/commit/dd7761b51e1775350be1782370aa22c0b0fe98d7
> bump crate version to 0.2.0

- Cargo.toml
- README.md
- examples/access_keys.rs
- examples/auth.rs
- examples/contract_change_method.rs
- examples/contract_view_code.rs
- examples/contract_view_method.rs
- examples/query_final_block.rs
- examples/utils.rs
- examples/view_account.rs
Add useful examples to the repo like calling contract view/change methods, downloading contract code, authentication, querying final block, etc.
Running an example: `cargo run --example view_account`
> chore: add examples to repo

- examples/utils.rs
- src/lib.rs
Allows owned `Strings` to be passed as urls to the `connect` method. Saves the extra internal allocation.
Before:
```rust
JsonRpcClient::connect("https://some-url.com");
let url: String = some_input();
JsonRpcClient::connect(url.as_str());
```
After:
```rust
JsonRpcClient::connect("https://some-url.com");
JsonRpcClient::connect(some_input());
```
> feat: connect with generic AsUrl

- src/lib.rs
Default the `JsonRpcClient`'s authentication state to being `Unauthenticated`, much like `HashMap`'s `RandomState`. Makes it so you don't have to worry about authentication until you actually need to. So the `auth` module shouldn't be imported without you doing any authentication.
```diff
-use near_jsonrpc_client::{auth, JsonRpcClient};
+use near_jsonrpc_client::JsonRpcClient;
struct App {
-    client: JsonRpcClient<auth::Unauthenticated>, // <-- pain
+    client: JsonRpcClient,
}
enum Network {
MainNet,
TestNet,
}
- fn mk_client(network: Network) -> JsonRpcClient<auth::Unauthenticated> { // <-- pain
+ fn mk_client(network: Network) -> JsonRpcClient {
let rpc_url = match network {
Network::MainNet => "https://rpc.mainnet.near.org",
Network::TestNet => "https://rpc.testnet.near.org",
}; …
```
> feat: JsonRpcClient, default to Unauthenticated state

- .github/workflows/rustdoc.yml
First, we stick to using the `ubuntu-20.04` image, and then, according to https://github.com/actions/virtual-environments/blob/e5d8f5af5c5dfef051432b3cd33d5078331cc1b5/images/linux/Ubuntu2004-Readme.md#rust-tools;
> ### Rust Tools
>  - Cargo 1.58.0
>  - Rust 1.58.1
>  - Rustdoc 1.58.1
>  - Rustup 1.24.3
Rust is already preinstalled right out of the box for this image, so we can skip the installation step.
> chore(ci): skip rust installation in rustdoc pipeline

- .github/workflows/ci.yml
- Cargo.toml
- README.md
Following https://github.com/near/borsh-rs/pull/67, this PR introduces a CI job that automates versioning and publishing this crate to crates.io.
> feat(infra): introduce automated publishing

- CHANGELOG.md
- Cargo.toml
- src/methods.rs
After https://github.com/near/nearcore/pull/6158, neard client supports fast forwarding to a specific height. This implements client support for that.
```rust
let client = JsonRpcClient::connect("http://localhost:3030");
client.call(
methods::sandbox_fast_forward::RpcSandboxFastForwardRequest {
delta_height: 10_000,
},
);
```
Translates directly to 👇🏽 
```console
xh http://localhost:3030 \
jsonrpc=2.0 id=dontcare \
method=sandbox_fast_forward params:='{ "delta_height": 10000 }'
```
> feat(sandbox): impl client support for fast forwarding

- Cargo.toml
Current (`v0.3.0`) build of the doc on docs.rs – https://docs.rs/near-jsonrpc-client/0.3.0/near_jsonrpc_client/methods/index.html doesn't include any sandbox methods or the “any” helper function. This remedies that.
However, this **still** excludes all adversarial methods.
> docs.rs: document the `any` helper and `sandbox` RPC methods

- Cargo.toml
- examples/utils.rs
- src/lib.rs
Introduce the `auth` feature flag (selected by default), making the `uuid` dependency conditionally optional.
> chore: move auth-specific logic behind the default `auth` feature flag

- src/methods/gas_price.rs
Fixes serialization with the `gas_price` RPC method.
Related upstream fix: https://github.com/near/nearcore/pull/6532
> fix: `gas_price` RPC method serialization

- src/methods/block.rs
Documented the `block` RPC method, including easy-to-understand examples.
Examples are included showing how a block can be queried using all of the [BlockReference](https://docs.rs/near-primitives/0.12.0/near_primitives/types/enum.BlockReference.html) variants: 
- `BlockId`
- `BlockHeight`: Fetch a block by its height
- `BlockHash`: Fetch a block by its hash
- `Finality`
- `None`:  Returns the latest block recorded on the node that responds to the query (An optimistic request)
- `Final`: Returns the latest finalised block (validated on at least 66% of the nodes in the network)
- `SyncCheckpoint`
- `Genesis`: Returns the block at the first Sync Checkpoint after the network's genesis block.
- `EarliestAvailable`: …
> chore(docs): document the `block` RPC method

- src/methods/chunk.rs
Documented the `chunk` RPC method, including easy-to-understand examples.
> chore(docs): document the `chunk` RPC method

- src/methods/network_info.rs
Tracking issue: https://github.com/near/near-jsonrpc-client-rs/issues/51
Documented the `network_info` RPC method, including an easy-to-understand example.
> chore(docs): document the `network_info` RPC method

- src/methods/light_client_proof.rs
Documented the `light_client_proof` RPC method, including an easy-to-understand example.
> chore(docs): document the `light_client_proof` RPC method

- src/methods/status.rs
Tracking issue: https://github.com/near/near-jsonrpc-client-rs/issues/51
Documented the `status` RPC method, including an easy-to-understand example.
> chore(docs): document the `status` RPC method

- src/methods/health.rs
Tracking issue: https://github.com/near/near-jsonrpc-client-rs/issues/51
Documented the `health` RPC method, including an easy-to-understand example.
> chore(docs): document the `health` RPC method

- examples/contract_change_method_commit.rs
New example demonstrating how to construct and send a request to an RPC node using the `broadcast_tx_commit` method.
> feat(examples): contract_change_method example using the `broadcast_tx_commit` RPC method

- examples/utils.rs
The network selector for examples couldn't properly select the custom option by index.
> fix examples network selector by index

- src/errors.rs
- src/methods/block.rs
- src/methods/chunk.rs
- src/methods/experimental/protocol_config.rs
- src/methods/gas_price.rs
- src/methods/light_client_proof.rs
- src/methods/mod.rs
- src/methods/next_light_client_block.rs
Further context: https://github.com/near/near-jsonrpc-client-rs/pull/29
This workaround should've been applied on the `.error_struct` variant and not `.data`.
> fix: unserialized error compat is exclusively for `.error_struct`, not `.data`

- examples/create_account.rs
Allow floating point deposit input up to 6 fractional points.
Before: `1`, `2`, `400`
Now: `1`, `0.5`, `748.185928`
Anything beyond 6 fractional points gets truncated.
Example: `982.37283729475` gets truncated to `982.372837`
> feat: allow floating point deposits with create-account example

- Cargo.toml
- examples/access_keys.rs
- examples/auth.rs
- examples/contract_change_method.rs
- examples/contract_change_method_commit.rs
- examples/contract_view_code.rs
- examples/contract_view_method.rs
- examples/create_account.rs
- examples/query_block.rs
- examples/view_account.rs
- src/lib.rs
Add logging to aid intermediate inspection of the request / response payloads.
> feat: add logging

- Cargo.toml
- examples/create_account.rs
- src/lib.rs
- src/methods/block.rs
- src/methods/chunk.rs
- src/methods/light_client_proof.rs
- src/methods/tx.rs
Updates nearcore dependencies to `0.14.0`. https://github.com/near/nearcore/pull/6918
This update restores compatibility with nodes, after a breaking change was introduced.
> chore: update nearcore dependencies

- CHANGELOG.md
- Cargo.toml
Scheduled release: 31-05-2022
Intermediate version before [`0.4.0`](https://github.com/near/near-jsonrpc-client-rs/pull/83).
Notable changes:
- Updated nearcore dependencies, fixing a previous breaking change. <https://github.com/near/near-jsonrpc-client-rs/pull/100>
- Fixed `query` method error deserialization. <https://github.com/near/near-jsonrpc-client-rs/pull/82>
- Fixed `gas_price` RPC method serialization. <https://github.com/near/near-jsonrpc-client-rs/pull/73>
- Reworked the `JsonRpcError`::`handler_error` method. <https://github.com/near/near-jsonrpc-client-rs/pull/99>
- Moved auth specific logic behind a feature flag. <https://github.com/near/near-jsonrpc-client-rs/pull/55>
- Added the `methods::to_json()` helper method for visualizing the serialization of the RPC methods. …
> chore: version to `0.4.0-beta.0`

- Cargo.toml
- README.md
I ran into an issue while cross-compiling near-jsonrpc-client-rs that openssl was not available in my cross compiler environment. This adds a feature flag to enable the rustls version of reqwest instead, which works much better with cross compiling.
> Add "rustls-tls" feature flag to enable rustls-tls feature in reqwest instead of native-tls.

- .gitignore
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/create_account.rs
- src/lib.rs
The NEAR crates need to be updated to unblock other libraries that are already or planning to use 0.15 of these crates.
A new version should be published following this pull.
Do note that there is a CI failure which I recommend the authors fix prior to pulling this in, but it is out of scope for this PR.
> chore: update to 0.15.0 of NEAR crates

- CHANGELOG.md
- Cargo.toml
Updated some, and just loosened the semver constraints for “trusted” dependencies.
@matklad, what do you think? Is this an antipattern?
> chore: update deps

- CHANGELOG.md
- Cargo.toml
- README.md
Scheduled release: 04-10-2022
Notable Changes:
- Updated nearcore dependencies, which now requires a MSRV of `1.64.0`. <https://github.com/near/near-jsonrpc-client-rs/pull/100>, <https://github.com/near/near-jsonrpc-client-rs/pull/110>
- Updated other dependencies, with some general improvements. <https://github.com/near/near-jsonrpc-client-rs/pull/111>
- Added `rustls-tls` feature flag to enable `rustls` as an alternative to `native-tls`. <https://github.com/near/near-jsonrpc-client-rs/pull/103>
- Switched to using `log::debug!` instead of `log::info!` for debug logging. <https://github.com/near/near-jsonrpc-client-rs/pull/107>
- Fixed `gas_price` RPC method serialization. <https://github.com/near/near-jsonrpc-client-rs/pull/73>
- Fixed `query` method error deserialization. …
> chore: version to 0.4.0

- .github/workflows/ci.yml
Include a line in the release that mentions the contributors of that release.
In the [last release](https://github.com/near/near-jsonrpc-client-rs/releases/tag/v0.4.0), I did this manually, but going forward, this too, will be automated!
> <img width="746" alt="CleanShot 2022-10-04 at 11 40 45@2x" src="https://user-images.githubusercontent.com/16881812/193762460-fc7fbeb3-a0d3-416e-8b7a-a8b28c164727.png">
<details>
<summary> Example CI run </summary>
https://github.com/near/near-jsonrpc-client-rs/actions/runs/3180382701/jobs/5183887099
</details>
> highlight the contributors in every release

- CHANGELOG.md
- Cargo.toml
- src/methods/mod.rs
- src/methods/query.rs
Small nit, but the client was parsing `&RpcMethod`'s differently from `RpcMethod`s.
Leading to the `data did not match any variant of untagged enum QueryResponseKind` error when you run `client.call(&method)`.
> &RpcMethod response handling should match RpcMethod's

- src/auth.rs
Resolves #115. Removes the `Display` implementation on `ApiKey`. I would've otherwise have deprecated this, but rust [does not support](https://github.com/rust-lang/rust/issues/39935) `#[deprecated]` annotations on implementations.
> chore: deprecate `Display` impl for `ApiKey`

- CHANGELOG.md
- src/auth.rs
- src/header.rs
- src/lib.rs
Resolves #118.
Introduces the `Authorization::bearer` method that adds an equivalent `Authorization: Bearer ...` entry into the request headers.
This function does no input validation beyond that it's a header value, not that it's a valid JWT.
We offload the guarantee of it being a valid utf-8 string to the caller.
> introduce Authorization::bearer helper method

- CHANGELOG.md
- Cargo.toml
- src/methods/mod.rs
- src/methods/query.rs
needed for releasing the relayer used for meta transactions https://github.com/near/pagoda-relayer-rs/pull/1 and cli changes https://github.com/near/near-cli-rs/pull/151
- update `near-primitives` and associated crates to `0.16.0`
- downgrade tokio to `1.19.0` to be compatible with `near-primitives` subdependency versions of `tokio`
- fix signature type bug introduced in https://github.com/near/nearcore/pull/8460
- updated error msg str - see https://github.com/near/near-jsonrpc-client-rs/pull/122#issuecomment-1442527306
- bump `rust-version` to `1.67.1` after https://github.com/near/nearcore/pull/8456.
> updated near-primitives and associated crates

- CHANGELOG.md
- Cargo.toml
- README.md
Scheduled Release: 24-02-2023
- `ApiKey::new` now accepts byte arrays and byte slices. <https://github.com/near/near-jsonrpc-client-rs/pull/119>
- `Authorization::bearer` method for token-authenticated requests. <https://github.com/near/near-jsonrpc-client-rs/pull/121>
- `ApiKey::as_bytes` returns a byte slice of the key without utf-8 validation. <https://github.com/near/near-jsonrpc-client-rs/pull/119>
- Updated nearcore dependencies to `0.16.0`, which now requires a MSRV of `1.67.1`. <https://github.com/near/near-jsonrpc-client-rs/pull/122>
- `ApiKey::new` no longer requres the input of a valid UUID. <https://github.com/near/near-jsonrpc-client-rs/pull/119>
- `Debug` on `ApiKey` doesn't reveal the key anymore. <https://github.com/near/near-jsonrpc-client-rs/pull/120>
- The `auth` module …
> chore: version to 0.5.0

- examples/contract_view_state.rs
This is a barebones example that dumps the low-level state as is. In the future we might want to make it nicer or point to near.cli.rs for the demo (https://github.com/near/near-cli-rs/issues/223)
> feat: Added a new example to view contract state

- src/methods/any/mod.rs
Documented the generic `methods::any()` constructor
> chore(docs): document the generic `methods::any()` constructor

- src/methods/sandbox/patch_state.rs
Documented the `sandbox_patch_state` RPC method, including an easy-to-understand example.
> chore(docs): document the `sandbox_patch_state` RPC method

- src/methods/broadcast_tx_commit.rs
Documented the `broadcast_tx_commit` RPC method, including an easy-to-understand example.
> chore(docs): document the `broadcast_tx_commit` RPC method

- src/methods/broadcast_tx_async.rs
Documented the `broadcast_tx_async` RPC method, including an easy-to-understand example.
> chore(docs): document the `broadcast_tx_async` RPC method

- src/methods/next_light_client_block.rs
Documented the `next_light_client_block` RPC method, including an easy-to-understand example.
> chore(docs): document the `next_light_client_block` RPC method

- src/methods/validators.rs
Documented the `validators` RPC method, including easy-to-understand examples.
> chore(docs): document the `validators` RPC method

- src/methods/sandbox/fast_forward.rs
Documented the `sandbox_fast_forward` RPC method, including an easy-to-understand example.
> chore(docs): document the `sandbox_fast_forward` RPC method

- src/methods/experimental/check_tx.rs
Documented the `EXPERIMENTAL_check_tx` RPC method, including an easy-to-understand example.
> chore(docs): document the `EXPERIMENTAL_check_tx` RPC method

- src/methods/experimental/changes.rs
Documented the `EXPERIMENTAL_changes` RPC method, including easy-to-understand examples.
> chore(docs): document the `EXPERIMENTAL_changes` RPC method

- src/methods/gas_price.rs
Documented the `gas_price` RPC method, including easy-to-understand examples.
> chore(docs): document the `gas_price` RPC method

- src/methods/experimental/validators_ordered.rs
Documented the experimental `validators_ordered` RPC method, including an easy-to-understand example.
> chore(docs): document the experimental `validators_ordered` RPC method

- src/methods/experimental/receipt.rs
Documented the `EXPERIMENTAL_receipt` RPC method, including an easy-to-understand example.
> chore(docs): document the `EXPERIMENTAL_receipt` RPC method

- src/methods/experimental/changes_in_block.rs
Documented the `EXPERIMENTAL_changes_in_block` RPC method, including an easy-to-understand example.
> chore(docs): document the `EXPERIMENTAL_changes_in_block` RPC method

- src/methods/experimental/protocol_config.rs
Documented the `EXPERIMENTAL_protocol_config` RPC method, including an easy-to-understand example.
> chore(docs): document the `EXPERIMENTAL_protocol_config` RPC method

- src/methods/experimental/genesis_config.rs
Documented the experimental `genesis_config` RPC method, including an easy-to-understand example.
> chore(docs): document the experimental `genesis_config` RPC method

- src/methods/experimental/tx_status.rs
Documented the experimental `tx_status` RPC method, including an easy-to-understand example.
> chore(docs): document the experimental `tx_status` RPC method

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.6.0 -> 0.7.0 (✓ API compatible changes)
<blockquote>
- Added a new example to view contract state ([#129](https://github.com/near/near-jsonrpc-client-rs/pull/129))
- Fixed doc tests after the recent crate updates ([#135](https://github.com/near/near-jsonrpc-client-rs/pull/135))
- *(docs)* revise crate-level docs ([#88](https://github.com/near/near-jsonrpc-client-rs/pull/88))
- *(docs)* revise README docs ([#91](https://github.com/near/near-jsonrpc-client-rs/pull/91))
- *(docs)* revise module-level docs for RPC methods ([#87](https://github.com/near/near-jsonrpc-client-rs/pull/87))
- *(docs)* document the experimental `tx_status` RPC method ([#63](https://github.com/near/near-jsonrpc-client-rs/pull/63))
- …
> chore: release v0.7.0

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.7.0 -> 0.8.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] Upgraded NEAR crates to 0.20.0 release ([#137](https://github.com/near/near-jsonrpc-client-rs/pull/137))
</blockquote>
</p></details>
---
> chore: release v0.8.0

- src/methods/broadcast_tx_async.rs
- src/methods/send_tx.rs
- Fixes #141: removed array creation for parameters in fn params() implementation for send_tx method
- Fixes #143: From trait for RpcBroadcastTxAsyncRequest
> Fix: removed array creation for parameters in fn params() implementation for send_tx method

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.8.0 -> 0.9.0 (⚠️ API breaking changes)
```
--- failure constructible_struct_adds_field: externally-constructible struct adds field ---
Description:
A pub struct constructible with a struct literal has a new pub field. Existing struct literals must be updated to include the new field.
ref: https://doc.rust-lang.org/reference/expressions/struct-expr.html
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.30.0/src/lints/constructible_struct_adds_field.ron
Failed in:
field RpcTransactionStatusRequest.wait_until in /tmp/.tmpXtONiN/near-jsonrpc-client-rs/src/methods/experimental/tx_status.rs:43
field RpcTransactionStatusRequest.wait_until in /tmp/.tmpXtONiN/near-jsonrpc-client-rs/src/methods/tx.rs:46
--- failure module_missing: pub module removed or …
```
> chore: release v0.9.0

- Cargo.toml
I have updated the near-core libraries to the latest 0.22 release.
> chore: upgraded near libraries and reqwest to the latest version

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.9.0 -> 0.10.0
<blockquote>
- expose `ChunkReference` type used in chunk call ([#144](https://github.com/near/near-jsonrpc-client-rs/pull/144))
- [**breaking**] Upgraded libraries to the latest versions: near-* 0.22 and reqwest 0.12 ([#145](https://github.com/near/near-jsonrpc-client-rs/pull/145))
</blockquote>
</p></details>
---
> chore: release v0.10.0

- Cargo.toml
~Technically it is a breaking change since we now depend on the newer version of near-* crates and thus the upstream dependencies should also update them.~
It is not a breaking change since developers can still use the older near-* versions
> chore: Updated near-deps to 0.23.0

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.10.0 -> 0.10.1
<blockquote>
- Updated near-deps to 0.23.0 ([#148](https://github.com/near/near-jsonrpc-client-rs/pull/148))
</blockquote>
</p></details>
---
> chore: release v0.10.1

- Cargo.toml
- examples/contract_change_method.rs
- examples/contract_change_method_commit.rs
- examples/create_account.rs
- examples/query_tx.rs
- examples/send_tx.rs
- examples/view_account.rs
- rust-toolchain.toml
- src/methods/broadcast_tx_async.rs
- src/methods/broadcast_tx_commit.rs
- src/methods/send_tx.rs
> chore: updated near-* to 0.24.0

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.10.1 -> 0.10.2
<blockquote>
- updated near-* crates to allow 0.24.0 in addition to all the previously supported versions ([#151](https://github.com/near/near-jsonrpc-client-rs/pull/151))
</blockquote>
</p></details>
---
> chore: release v0.10.2

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.11.0 -> 0.12.0
<blockquote>
- updated near-* to 0.25.0 ([#154](https://github.com/near/near-jsonrpc-client-rs/pull/154))
</blockquote>
</p></details>
---
> chore: release v0.12.0

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.12.0 -> 0.13.0
<blockquote>
- [**breaking**] updates near-* dependencies to 0.26 release ([#157](https://github.com/near/near-jsonrpc-client-rs/pull/157))
</blockquote>
</p></details>
---
> chore: release v0.13.0

- src/errors.rs
- src/lib.rs
https://github.com/near/near-jsonrpc-client-rs/issues/159
> Add http errors 400, 408, 503, 500

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.15.0 -> 0.15.1 (✓ API compatible changes)
<blockquote>
- fixed test compilation (#165)
</blockquote>
</p></details>
---
> chore: release v0.15.1

- Cargo.toml
- examples/contract_change_method.rs
- examples/contract_change_method_commit.rs
- examples/create_account.rs
- examples/send_tx.rs
- rust-toolchain.toml
- src/methods/broadcast_tx_async.rs
- src/methods/broadcast_tx_commit.rs
- src/methods/send_tx.rs
- src/methods/validators.rs
@race-of-sloths
For now, 2.5.0 is rolled back for nodes, so we don't have a running RPC node with the latest changes. Unfortunately, the test can't pass on the mainnet, so I have changed it to testnet to unblock the rollout of the crates (https://github.com/near/near-jsonrpc-client-rs/pull/169/commits/ee966c0f6c9be87a9926ffb381b855a5ae11dd0b). The issue tracked in #170
> chore!: updates near-* dependencies to 0.29 release

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.15.1 -> 0.16.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] updates near-* dependencies to 0.29 release ([#169](https://github.com/near/near-jsonrpc-client-rs/pull/169))
- added CODEOWNERS ([#167](https://github.com/near/near-jsonrpc-client-rs/pull/167))
</blockquote>
</p></details>
---
> chore: release v0.16.0

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.16.0 -> 0.16.1 (✓ API compatible changes)
<blockquote>
- Fixed missing serde::Serialize on BroadcastTxAsync and GenesisConfig errors ([#171](https://github.com/near/near-jsonrpc-client-rs/pull/171))
</blockquote>
</p></details>
---
> chore: release v0.16.1

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.16.1 -> 0.17.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] updates near-* dependencies to 0.30 release ([#174](https://github.com/near/near-jsonrpc-client-rs/pull/174))
</blockquote>
</p></details>
---
> chore: release v0.17.0

- CHANGELOG.md
- Cargo.toml
* `near-jsonrpc-client`: 0.17.0 -> 0.18.0 (✓ API compatible changes)
<blockquote>
- [**breaking**] update near-* dependencies to 0.31 release ([#177](https://github.com/near/near-jsonrpc-client-rs/pull/177))
</blockquote>
</p></details>
---
> chore: release v0.18.0
